# Write your MySQL query statement belo
SELECT PRODUCT_ID , 'store1' AS store , STORE1 as price FROM PRODUCTS
WHERE STORE1 IS NOT NULL
UNION
SELECT PRODUCT_ID , 'store2' AS store , STORE2 as price FROM PRODUCTS
WHERE STORE2 IS NOT NULL
UNION
SELECT PRODUCT_ID , 'store3' AS store , STORE3 as price FROM PRODUCTS
WHERE STORE3 IS NOT NULL;
